#name: CD Pipeline
#
#on:
#  workflow_run:
#    workflows:
#      - CI Pipeline
#    types:
#      - completed
#
#
#jobs:
#  deploy:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Deploy Docker Container
#        uses: appleboy/ssh-action@v0.1.7
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          port: ${{ secrets.REMOTE_PORT }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            # Login to Docker Hub
#            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
#              -u "${{ secrets.DOCKER_USERNAME }}" \
#              --password-stdin
#
#            # Pull latest image
#             docker pull ${{ secrets.DOCKER_IMAGE }}:latest
#
#              docker logout
#
#
#            # Stop and remove old container
#             docker stop project-one || true
#             docker rm project-one || true
#
#            # Remove old image (optional)
#             docker image prune -f
#
#            # Run new container
#             docker run -d \
#              --name project-one \
#              --restart unless-stopped \
#              -p 8081:8080 \
#              ${{ secrets.DOCKER_IMAGE }}:latest